version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: root
    ports: 
      - '8080:8080'
      - '50000:50000'
    volumes:
      - ./jenkins_home:/var/jenkins_home

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    ports: 
      - '2222:22'
      - '80:80'
    volumes: 
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   restart: always
  #   depends_on: 
  #     - jenkins
  #     - gitlab
  #   volumes:
  #     - ./nginx/conf.d/:/etc/nginx/conf.d
  #   ports:
  #     - 8081:80